core/urls.py
from django.urls import path, include

from academics.subviews import classView, studentView
from iSOFTLIMS import utils
from . import views
from core.subviews import AdminViews, StudentViews, StudentAdminAffairs, ApplicantViews, UserViews
from django.contrib.auth import views as auth_views

urlpatterns = [
    # HOMEPAGE URL
    path("", views.loginPage, name="login"),
    path("login", views.loginPage, name="login"),
    path("register/", views.applicantloginPage, name="register"),
    path("doSignUp/", ApplicantViews.applicantsignup, name="doSignUp"),  # type: ignore
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("applicant_home/", ApplicantViews.applicant_home, name="applicant_home"),  # type: ignore
    path("user_home/", UserViews.user_home, name="user_home"),

    # USER CRUD URLS
    path("doLogin/", views.doLogin, name="doLogin"),
    path("get_user_details/", views.get_user_details, name="get_user_details"),
    path("logout_user/", views.logout_user, name="logout_user"),
    path("activate_account", views.activate_account, name="activate_account"),
    path("activate_user/<user_id>", AdminViews.activate_user, name="activate_user"),
    path(
        "deactivate_user/<user_id>", AdminViews.deactivate_user, name="deactivate_user"
    ),

    # ADMIN URLS
    path("admin_home/", AdminViews.admin_home, name="admin_home"),
    path("manage_users/", AdminViews.manage_users, name="manage_users"),

    # SCHOOL PROFILE URLS
    path("admin_profile/", AdminViews.admin_profile, name="admin_profile"),
    path("admin_profile_update/", AdminViews.admin_profile_update, name="admin_profile_update"),
    path("school_profile/", AdminViews.school_profile, name="school_profile"),
    path("admin_school_update/", AdminViews.admin_school_update, name="admin_school_update"),

    # ADMINISTRATION URLS:
    path("administration/", AdminViews.administration, name="administration"),
    path("add_campus/", AdminViews.add_campus, name="add_campus"),
    path("edit_campus/<campus_id>", AdminViews.edit_campus, name="edit_campus"),
    path("delete_campus/<campus_id>", AdminViews.delete_campus, name="delete_campus"),
    path("schools/", AdminViews.school, name="schools"),
    path("add_school/", AdminViews.add_school, name="add_school"),
    path("edit_school/<school_id>", AdminViews.edit_school, name="edit_school"),
    path("delete_school/<school_id>", AdminViews.delete_school, name="delete_school"),

    # ADMISSIONS
    path("admissions/", AdminViews.admissions, name="admissions"),
    path("admissions_approve/", AdminViews.admissions_approve, name="admissions_approve"),
    path("dvc_approve/", AdminViews.dvc_approve, name="dvc_approve"),

    # DEPARTMENT MANAGEMENT URLS
    path("manage_department/", AdminViews.manage_departments, name="manage_departments"),
    path("add_department/", AdminViews.add_department, name="add_department"),
    path("add_department_save/", AdminViews.add_department_save, name="add_department_save"),
    path("edit_department/<department_id>/", AdminViews.edit_department, name="edit_department"),
    path("edit_department_save/", AdminViews.edit_department_save, name="edit_department_save"),
    path("delete_department/<department_id>/", AdminViews.delete_department, name="delete_department"),
    path("manage_staff_type/", AdminViews.manage_staff_type, name="manage_staff_type"),
    path("create_staff_type/", AdminViews.create_staff_type, name="create_staff_type"),

    # HOD URLS
    path("manage_hod/", AdminViews.manage_hods, name="manage_hod"),
    path("add_hod/", AdminViews.add_hod, name="add_hod"),
    path("add_hod_save/", AdminViews.add_hod_save, name="add_hod_save"),
    path("edit_hod/<hod_id>/", AdminViews.edit_hod, name="edit_hod"),
    path("edit_hod_save/", AdminViews.edit_hod_save, name="edit_hod_save"),
    path("delete_hod/<hod_id>/", AdminViews.delete_hod, name="delete_hod"),

    # MANAGE COURSE
    path("manage_courses/", AdminViews.manage_courses, name="manage_courses"),
    path("add_course/", AdminViews.add_course, name="add_course"),
    path("add_course_save/", AdminViews.add_course_save, name="add_course_save"),
    path("check_if_course_exists/", AdminViews.check_if_course_exists, name="check_if_course_exists"),
    path("edit_course/<course_id>", AdminViews.edit_course, name="edit_course"),
    path("delete_course/<course_id>", AdminViews.delete_course, name="delete_course"),

    # STAFF URLS
    path("add_staff/", AdminViews.add_staff, name="add_staff"),
    path("add_staff_save/", AdminViews.add_staff_save, name="add_staff_save"),
    path("manage_staff/", AdminViews.manage_staff, name="manage_staff"),
    path("edit_staff/<staff_id>/", AdminViews.edit_staff, name="edit_staff"),
    path("edit_teacher/<teacher_id>/", AdminViews.edit_teacher, name="edit_teacher"),
    path("edit_staff_save/", AdminViews.edit_staff_save, name="edit_staff_save"),
    path("edit_teacher_save/", AdminViews.edit_teacher_save, name="edit_teacher_save"),
    path("delete_staff/<staff_id>/", AdminViews.delete_staff, name="delete_staff"),
    path("delete_teacher/<teacher_id>/", AdminViews.delete_teacher, name="delete_teacher"),

    # STUDENT URLS
    path("student_home", StudentViews.student_home, name="student_home"),
    path("student_profile/", StudentViews.student_profile, name="student_profile"),
    path("student_sessions/", StudentViews.enroll_session, name="enroll_session"),
    path("enroll_session_save/<enrollment_id>", StudentViews.enroll_session_save, name="enroll_session_save"),
    path("student_classes/", StudentViews.enroll_classes, name="enroll_classes"),
    path("enroll_class_save/", StudentViews.enroll_class_save, name="enroll_class_save"),
    path("student_apply_leave/", StudentViews.student_apply_leave, name="student_apply_leave"),
    path("student_apply_leave_save/", StudentViews.student_apply_leave_save, name="student_apply_leave_save"),
    path("student_feedback/", StudentViews.student_feedback, name="student_feedback"),
    path("student_feedback_save/", StudentViews.student_feedback_save, name="student_feedback_save"),
    path("student_profile/", StudentViews.student_profile, name="student_profile"),
    path("student_profile_update/", StudentViews.student_profile_update, name="student_profile_update"),
    path("student_view_result/", StudentViews.student_view_result, name="student_view_result"),

    path("student_housing/", StudentViews.student_housing, name="student_housing"),
    path("book_housing/<house_id>", StudentViews.book_housing, name="book_housing"),
    



    path("add_student/", AdminViews.add_student, name="add_student"),
    path("add_student_save/", AdminViews.add_student_save, name="add_student_save"),
    path("edit_student/<student_id>", AdminViews.edit_student, name="edit_student"),
    path("edit_student_save/", AdminViews.edit_student_save, name="edit_student_save"),
    path("manage_students/", AdminViews.manage_students, name="manage_students"),
    path("delete_student/<student_id>/", AdminViews.delete_student, name="delete_student"),
    path("student_session_management/", StudentViews.students_sessions_management, name="students_sessions_management"),
    path("defer_student/", StudentViews.defer_student, name="defer_student"),
    path("withdraw_student/", StudentViews.withdraw_student, name="withdraw_student"),
    path("student_affairs/", StudentAdminAffairs.student_affairs_home, name="student_affairs"),
    path("manage_student_approvals/", StudentAdminAffairs.manage_student_approvals, name="manage_student_approvals"),
    path("confirm_defer_student/", StudentAdminAffairs.confirm_defer_student, name="confirm_defer_student"),
    path("deny_defer_student/", StudentAdminAffairs.deny_defer_student, name="deny_defer_student"),
    path("manage_temporary_approvals/", StudentAdminAffairs.manage_temporary_approvals, name="manage_temporary_approvals"),
    path("confirm_temporary_defer/", StudentAdminAffairs.confirm_temporary_defer, name="confirm_temporary_defer"),
    path("deny_temporary_defer/", StudentAdminAffairs.deny_temporary_defer, name="deny_temporary_defer"),
    path("manage_interfaculty_transfer/", StudentAdminAffairs.manage_interfaculty_transfer, name="manage_interfaculty_transfer"),
    path("confirm_interfaculty_transfer/", StudentAdminAffairs.confirm_interfaculty_transfer, name="confirm_interfaculty_transfer"),
    path("deny_interfaculty_transfer/", StudentAdminAffairs.deny_interfaculty_transfer, name="deny_interfaculty_transfer"),
    path("manage_guardians/", AdminViews.manage_guardians, name="manage_guardians"),
    path("add_guardians/", AdminViews.add_guardian, name="add_guardian"),
    path("add_guardian_save/", AdminViews.add_guardian_save, name="add_guardian_save"),
    path("edit_guardian/<guardian_id>/", AdminViews.edit_guardian, name="edit_guardian"),
    path("edit_guardian_save/", AdminViews.edit_guardian_save, name="edit_guardian_save"),
    path("delete_guardian/<guardian_id>/", AdminViews.delete_student, name="delete_guardian"),

    path("apply_interschool_transfer/", StudentAdminAffairs.apply_interschool_transfer, name="apply_interschool_transfer"),

finance/urls.py
from django.urls import path, include
from . import views
from finance import views
from .subviews import MainViews

app_name = "finance"


urlpatterns = [
    # path("finance", views.finance_home, name="finance_home"),
    path("", views.finance_home, name="finance_home"),
    path("add_transaction", views.add_transaction, name="add_transaction"),
    path("transaction_create", views.transaction_create, name='transaction_create'),
    path('approve_applications/', views.approve_applications, name="approve_applications"),
    path('approve/', views.approve, name="approve"),
    path('check_student_exist/', views.check_student_exist, name="check_student_exist"),

    # PAYMENT METHODS
    path("manage_payment_methods", MainViews.manage_payment_methods, name="manage_payment_methods"),
    path("add_payment_method", MainViews.add_payment_method, name="add_payment_method"),
    path("add_payment_method_save", MainViews.add_payment_method_save, name="add_payment_method_save"),
    path("edit_payment_method/<payment_method_id>", MainViews.edit_payment_method, name="edit_payment_method"),
    path("delete_payment_method/<payment_method_id>", MainViews.delete_payment_method, name="delete_payment_method"),
    # banks
    path("manage_banks", MainViews.manage_banks, name="manage_banks"),
    path("add_bank", MainViews.add_bank, name="add_bank"),
    path("add_bank_save", MainViews.add_bank_save, name="add_bank_save"),
    path("edit_bank/<bank_id>", MainViews.edit_bank, name="edit_bank"),
    path("delete_bank/<bank_id>", MainViews.delete_bank, name="delete_bank"),

    # billing ITEMS
    path("manage billing", MainViews.manage_billing_items, name="manage_billing_items"),
    path("add_billing_item", MainViews.add_billing_item, name="add_billing_item"),
    path("add_billing_item_save", MainViews.add_billing_item_save, name="add_billing_item_save"),
    path("edit_billing_item/<billing_item_id>", MainViews.edit_billing_item, name="edit_billing_item"),
    path("delete_billing_item/<billing_item_id>", MainViews.delete_billing_item, name="delete_billing_item"),

    # BILLING TEMPLATES
    path("manage_billing_templates", MainViews.manage_billing_templates, name="manage_billing_templates"),
    path("add_billing_template", MainViews.add_billing_template, name="add_billing_template"),
    path("add_billing_template_save", MainViews.add_billing_template_save, name="add_billing_template_save"),
    path("edit_billing_template/<billing_template_id>", MainViews.edit_billing_template, name="edit_billing_template"),
    path("delete_billing_template/<billing_template_id>", MainViews.delete_billing_template, name="delete_billing_template"),

    # STUDENT VIEWS
    # path("manage_billings/", MainViews.manage_billings, name="manage_billings"),
]

iSOFTLIMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.defaults import page_not_found
from django.contrib import admin


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("academics/", include("academics.urls")),
    path("finance/", include("finance.urls")),
    # zesting the inbuilt forms to add custom autocomplete
    path("select2/", include("django_select2.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, )+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'iSOFTLIMS.views.handler404'
handler500 = 'iSOFTLIMS.views.handler500'

admin.site.site_header = 'iSoft ADMINISTRATION'
admin.site.site_title = 'iSOFT'

core/forms/applicantforms.py
from django import forms
from django.forms import ClearableFileInput, DateInput
from django.utils.translation import gettext_lazy as _
from core.models import Applicant

class ApplicantForm(forms.ModelForm):
    # department = forms.CharField(max_length=100)
    # concept_paper = forms.FileField()
    # masters_degree_type = forms.CharField(max_length=100)
    # masters_degree_title = forms.CharField(max_length=100)
    # start_date = forms.DateField(label="Session End", widget=DateInput(attrs={"class": "form-control"}))
    # expected_completion_date = forms.DateField(label="Session End", widget=DateInput(attrs={"class": "form-control"}))
    # mode_of_study = forms.CharField(max_length=100)
    # photo_1 = forms.FileField()
    # photo_2 = forms.FileField()
    # secondary_schools_attended = forms.CharField(widget=forms.Textarea)
    # university_education = forms.CharField(widget=forms.Textarea)
    # other_degrees_or_diploma = forms.CharField(widget=forms.Textarea)
    # research_experience = forms.CharField(widget=forms.Textarea)
    # employment_work_experience = forms.CharField(widget=forms.Textarea)
    # languages_spoken = forms.CharField(widget=forms.Textarea)
    # referee1_name = forms.CharField(max_length=100)
    # referee1_designation = forms.CharField(max_length=100)
    # referee1_address = forms.CharField(widget=forms.Textarea)
    # referee1_telephone = forms.CharField(max_length=20)
    # referee1_email = forms.EmailField()
    # referee2_name = forms.CharField(max_length=100)
    # referee2_designation = forms.CharField(max_length=100)
    # referee2_address = forms.CharField(widget=forms.Textarea)
    # referee2_telephone = forms.CharField(max_length=20)
    # referee2_email = forms.EmailField()
    # how_did_you_know_about_us = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Applicant
        fields = '__all__'
        widgets = {
            # 'concept_paper': ClearableFileInput(attrs={'multiple': False}),
            # 'photo_1': ClearableFileInput(attrs={'multiple': False}),
            # 'photo_2': ClearableFileInput(attrs={'multiple': False}),
            # 'start_date': forms.DateInput(attrs={'type': 'date'}),
            # 'expected_completion_date': forms.DateInput(attrs={'type': 'date'}),
            
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['concept_paper'].required = False
        self.fields['photo_1'].required = False
        self.fields['photo_2'].required = False

    # def clean_concept_paper(self):
    #     concept_paper = self.cleaned_data['concept_paper']
    #     if concept_paper:
    #         # Check file size
    #         if concept_paper.size > 2 * 1024 * 1024:
    #             raise forms.ValidationError(_('File size must be under 2MB.'))
    #         # Check file type
    #         content_type = concept_paper.content_type.split('/')[0]
    #         if content_type not in ['application/pdf']:
    #             raise forms.ValidationError(_('Unsupported file type. Only PDF files are allowed.'))
    #     return concept_paper

    # def clean_photo_1(self):
    #     photo_1 = self.cleaned_data['photo_1']
    #     if photo_1:
    #         # Check file size
    #         if photo_1.size > 2 * 1024 * 1024:
    #             raise forms.ValidationError(_('File size must be under 2MB.'))
    #         # Check file type
    #         content_type = photo_1.content_type.split('/')[0]
    #         if content_type not in ['image']:
    #             raise forms.ValidationError(_('Unsupported file type. Only image files are allowed.'))
    #     return photo_1

    # def clean_photo_2(self):
    #     photo_2 = self.cleaned_data['photo_2']
    #     if photo_2:
    #         # Check file size
    #         if photo_2.size > 2 * 1024 * 1024:
    #             raise forms.ValidationError(_('File size must be under 2MB.'))
    #         # Check file type
    #         content_type = photo_2.content_type.split('/')[0]
    #         if content_type not in ['image']:
    #             raise forms.ValidationError(_('Unsupported file type. Only image files are allowed.'))
    #     return photo_2

core/templates/core_navigation_navbar.html
<div>
    <div class="d-flex">
        <div class="">
            <a class="btn btn-warning" href="{% url 'academics:manage_session' %}" role="button">
                Manage Sessions</a><br />&nbsp;
        </div>

        <div class="ml-2">
            <a class="btn btn-warning" href="{% url 'administration' %}" role="button">
                Manage Campuses</a><br />&nbsp;
        </div>
    
        <div class="ml-2">
            <a class="btn btn-warning" href="{% url 'schools' %}" role="button">
                Manage Schools</a><br />&nbsp;
        </div>
    
        <div class="ml-2">
            <a class="btn btn-warning" href="{% url 'manage_departments' %}" role="button">
                Manage Departments</a><br />&nbsp;
        </div>
    
        <div class="ml-2">
            <a class="btn btn-warning" href="{% url 'manage_courses' %}" role="button">
                Manage Courses</a><br />&nbsp;
        </div>
    
        <div class="ml-2">
            <a class="btn btn-warning" href="{% url 'academics:manage_class' %}" role="button">
                Manage Unit</a><br />&nbsp;
        </div>
    
        <div class="ml-2">
            <a class="btn btn-warning" href="{% url 'academics:clusterclass_list' %}" role="button">
                Manage Unit Clusters</a><br />&nbsp;
        </div>
    
        <div class="ml-2">
            <a class="btn btn-warning" href="{% url 'academics:manage_grade' %}" role="button">
                Grade Year</a><br />&nbsp;
        </div>

        <div class="ml-2">
            <a class="btn btn-warning" href="{% url 'academics:manage_class_progression' %}" role="button">
                Class Progression</a><br />&nbsp;
        </div>
        
    </div>

    <div class="d-flex">
        <div class="">
            <a class="btn btn-secondary" href="{% url 'manage_houses' %}" role="button">
                Manage Houses</a><br />&nbsp;
        </div>

        <div class="ml-2">
            <a class="btn btn-secondary" href="{% url 'manage_services' %}" role="button">
                Manage Services</a><br />&nbsp;
        </div>

        <div class="ml-2">
            <a class="btn btn-secondary" href="{% url 'manage_activities' %}" role="button">
                EC Activities</a><br />&nbsp;
        </div>


        <div class="ml-2">
            <a class="btn btn-secondary" href="{% url 'manage_jobs' %}" role="button">
                Jobs & Positions</a><br />&nbsp;
        </div>

        <div class="ml-2">
            <a class="btn btn-secondary" href="{% url 'manage_responsibilities' %}" role="button">
                Students & Board of Management Responsibilities</a><br />&nbsp;
        </div>

        <div class="ml-2">
            <a class="btn btn-secondary" href="{% url 'manage_disciplinary_issues' %}" role="button">
                Disciplinary Management</a><br />&nbsp;
        </div>

        <div class="ml-2">
            <a class="btn btn-secondary" href="{% url 'finance:manage_payment_methods' %}" role="button">
                Payment Methods</a><br />&nbsp;
        </div>

        <div class="ml-2">
            <a class="btn btn-secondary" href="{% url 'finance:manage_billing_items' %}" role="button">
                Fee Items</a><br />&nbsp;
        </div>

        <div class="ml-2">
            <a class="btn btn-secondary" href="{% url 'finance:manage_billing_templates' %}" role="button">
                Billing Templates</a><br />&nbsp;
        </div>

      
        <!-- Religions
        Currency  -->

    </div>

    <div class="d-flex">
        <div class="">
            <a class="btn btn-primary" href="{% url 'manage_interfaculty_transfer' %}" role="button">
                Manage Interfaculty Transfer</a><br />&nbsp;
        </div>


    </div>

</div>

core/templates/user_home.html
{% extends 'user_base_template.html' %} 
{% block page_title %} 
<b>User Home</b> 
{% endblock page_title %} 
{% block main_content %}
{% load static %}

<section class="content mx-2">

        <h3 class="text-bold">Hello-{{ user.first_name }} {{ user.last_name }} !</h3>

        <div class="row d-flex">
            <div class="col-md-12">
                <div class="row d-flex">
        
                  <div class="col-md-6">
                    <div class="card bg-dark text-white widget-visitor-card vh-25">
                      <div class="text-center"><!----></div>
                      <div class="card-block-small text-center">
                        <a
                          class="nav-link active h4 font-weight-bold"
                          href="{% url 'school_profile'%}"
                          role="tab"
                          aria-selected="true"
                          >
                          Admin Dashboard
                          <hr>
                        </a>
                      </div>
                      <div class="ml-3 mb-3">
                        <div class="font-weight-bold">Current Session: {{current_session.session_start_date }} to {{current_session.session_end_date }}</div>
                        <div class="font-weight-bold">Students In Session: {{student_count}}</div>
                        <div class="font-weight-bold">Teachers in Employment: {{teacher_count}}</div>
                        <div class="font-weight-bold">Staff In Employment: {{staff_count}}</div>

                      </div>
                    </div>
                  </div>

                  <div class="col-md-6">
                    <div class="card bg-gradient-success text-white widget-visitor-card">
                      <div class="text-center"><!----></div>
                      <div class="card-block-small text-center">
                        <a
                          class="nav-link active h4 text-light font-weight-bold"
                          href="{% url 'admin_home'%}"
                          role="tab"
                          aria-selected="true"
                          >
                          Academics Dashboard
                          <hr>
                        </a>
                      </div>
                      <div class="ml-3 mb-3">
                        <div class="font-weight-bold text-light">Pending Applicants: {{applicants_count}} </div>
                        <div class="font-weight-bold text-light">Course Count: {{course_count}}</div>
                        <div class="font-weight-bold text-light">Departments: {{departments}}</div>
                        <div class="font-weight-bold text-light">Pending Issues/Notifications: {{sessions_number}}</div>
                      </div>
                    </div>
                  </div>

        
                  <div class="col-md-6">
                    <div class="card bg-gradient-primary text-white widget-visitor-card">
                      <div class="text-center"><!----></div>
                      <div class="card-block-small text-center">
                        <a
                          class="nav-link active h4 font-weight-bold"
                          href="{% url 'finance:finance_home'%}"
                          role="tab"
                          aria-selected="true"
                          >
                          Finance Dashboard
                          <hr>
                        </a>
                      </div>
                      <div class="ml-3 mb-3">
                        <div class="font-weight-bold text-light">Pending Transactions: {{transactions_count}}</div>
                      </div>
                    </div>
                  </div>
        
                  
        
                  <div class="col-md-6">
                    <div class="card bg-gradient-info text-white widget-visitor-card">
                      <div class="text-center"><!----></div>
                      <div class="card-block text-center">
                        <a
                          class="nav-link active h4 font-weight-bold"
                          href="{% url 'academics:academics_home'%}"
                          role="tab"
                          aria-selected=""
                          >
                          Learning dashboard
                          <hr>
                        </a>
                      </div>
                      <div class="ml-3 mb-3">
                        <div class="font-weight-bold text-light">Session Enrollment Count: {{session_enrollment_count}}</div>
                      </div>
                    </div>
                  </div>

                  <div class="col-md-6">
                    <div class="card bg-warning text-white widget-visitor-card">
                      <div class="text-center"><!----></div>
                      <div class="card-block text-center">
                        <a
                          class="nav-link active h4 font-weight-bold"
                          href="{% url 'academics:manage_exams'%}"
                          role="tab"
                          aria-selected=""
                          >
                          Examinations dashboard
                          <hr>
                        </a>
                      </div>
                      <div class="ml-3 mb-3">
                        <div class="font-weight-bold text-dark">Examinations: {{exam_count}}</div>
                      </div>
                    </div>
                  </div>

                  <div class="col-md-6">
                    <div class="card bg-gradient-secondary text-white widget-visitor-card">
                      <div class="text-center"><!----></div>
                      <div class="card-block-small text-center">
                        <a
                          class="nav-link active h4 font-weight-bold"
                          href="{% url 'student_home'%}"
                          role="tab"
                          aria-selected="true"
                          >
                          Student Dashboard
                          <hr>
                        </a>
                      </div>
                      <div class="ml-3 mb-3">
                        <div class="font-weight-bold text-light">Pending Issues/Notifications: {{sessions_number}}</div>
                      </div>
                    </div>
                  </div>

                  <div class="col-md-6">
                    <div class="card bg-gradient-success text-white widget-visitor-card">
                      <div class="text-center text dark"><!----></div>
                      <div class="card-block-small text-center">
                        <a
                          class="nav-link active h4 font-weight-bold"
                          href="#"
                          role="tab"
                          aria-selected="true"
                          >
                          Teacher Dashboard
                          <hr class="light-dark">
                        </a>
                      </div>
                      <div class="ml-3 mb-3">
                        <div class="font-weight-bold text-light">Pending Issues/Notifications: {{sessions_number}}</div>
                      </div>
                    </div>
                  </div>


                  <div class="col-md-6">
                    <div class="card bg-gradient-dark text-white text-white widget-visitor-card">
                      <div class="text-center"><!----></div>
                      <div class="card-block text-center">
                        <a
                          class="nav-link active h4 font-weight-bold"
                          href="{% url 'academics:manage_session_registation'%}"
                          role="tab"
                          aria-selected=""
                          >
                          Parent dashboard
                          <hr>
                        </a>
                      </div>
                      <div class="ml-3 mb-3">
                        <div class="font-weight-bold text-light">Pending Issues/Notifications: {{sessions_number}}</div>
                      </div>
                    </div>
                  </div>

                    
        
                 <div class="col-md-12">
                <div class="card table-card latest-activity-card">
                  <div class="card-header border-0">
                    <h5 class="text-bold">General Correspondence</h5>
                  </div>
          
                </div>
              </div>
            </div>
           
          
        </div>
</section>

{% endblock main_content %}