academics/urls.py
from django.urls import path, include

from academics.subviews import TeacherViews, academicsViews, classView, sessionRegistrationView, examinationViews, sessionViews
from . import views
# from . import subviews.classView

app_name = 'academics'

urlpatterns = [

    path('', academicsViews.academics_home, name="academics_home"),
    
    path('teacher_home/', TeacherViews.teacher_home, name="teacher_home"), 

    # SESSION URLS
    path('manage_session/', sessionViews.manage_session, name="manage_session"),
    path('add_session/', sessionViews.add_session, name="add_session"),
    path('add_session_save/', sessionViews.add_session_save, name="add_session_save"),
    path('edit_session/<session_id>', sessionViews.edit_session, name="edit_session"),
    path('delete_session/<session_id>/', sessionViews.delete_session, name="delete_session"),

    
    # MANAGE SESSION REGISTATION URLS
    path('manage_session_registation/', sessionRegistrationView.manage_session_registation, name="manage_session_registation"), 
    path('enroll_student/',sessionRegistrationView.enroll_student, name='enroll_student'),
    path('mass_edit_enrolled',sessionRegistrationView.mass_edit_enrolled, name='mass_edit_enrolled'),
    path('confirm_enrollment/<enrolled_id>/', sessionRegistrationView.confirm_enrollment, name='confirm_enrollment'),
    path('revoke_enrollment/<enrolled_id>/', sessionRegistrationView.revoke_enrollment, name="revoke_enrollment"),

    # Grade Year URLS
    path('add_grade/', classView.add_grade, name="add_grade"),
    path('add_class_grade/', classView.add_grade_save, name="add_grade_save"),
    path('manage_grade/', classView.manage_grade, name="manage_grade"),
    path('edit_grade/<grade_id>/', classView.edit_grade, name="edit_grade"),
    path('delete_grade/<grade_id>/', classView.delete_grade, name="delete_grade"),

    # CLASS URLS
    path('add_class/', classView.add_class, name="add_class"),
    # path('add_class_save/', classView.add_class_save, name="add_class_save"),
    path('manage_class/', classView.manage_class, name="manage_class"),

    #class clusters
    # path('manage_clusters/', classView.clusterclass_detail, name="manage_clusters"),
    path('manage_clusters/', classView.clusterclass_list, name='clusterclass_list'),
    path('<int:pk>/', classView.clusterclass_detail, name='clusterclass_detail'),
    path('new/', classView.clusterclass_create, name='clusterclass_create'),
    path('edit_clusterclass/<int:clusterclass_id>', classView.clusterclass_edit, name='clusterclass_edit'),

    path('edit_class/<class_id>/', classView.edit_class, name="edit_class"),
    # path('edit_class_save/', classView.edit_class_save, name="edit_class_save"),
    path('delete_class/<class_id>/', classView.delete_class, name="delete_class"),

    # GRADE URLS
    path('add_grade/', classView.add_grade, name="add_grade"),
    path('add_grade_save/', classView.add_grade_save, name="add_grade_save"),
    path('manage_grade/', classView.manage_grade, name="manage_grade"),
    path('edit_grade/<grade_id>/', classView.edit_grade, name="edit_grade"),
    path('delete_grade/<grade_id>/', classView.delete_grade, name="delete_grade"),

    # CLASS PROGRESSION URLS
    path('add_class_progression/', classView.add_class_progression, name="add_class_progression"),
    path('add_class_progression_save/', classView.add_class_progression_save, name="add_class_progression_save"),
    path('manage_class_progression/', classView.manage_class_progression, name="manage_class_progression"),
    path('edit_class_progression/<class_progression_id>/', classView.edit_class_progression, name="edit_class_progression"),
    path('delete_class_progression/<class_progression_id>/', classView.delete_class_progression, name="delete_class_progression"),

    # MANAGE EXAMINATIONS
    path('manage_exams/', examinationViews.manage_examinations, name="manage_exams"),
    path('add_exam_type/', examinationViews.add_exam_type, name="add_exam_type"),
    path('add_grade_exam/', examinationViews.add_grade, name="add_grade_exam"),
    path('add_new_grade_exam/', examinationViews.add_new_grade, name="add_new_grade_exam"),
    path('mass_edit_student_exam', examinationViews.mass_edit_student_exam, name="mass_edit_student_exam"),
    

    #student management
    path('register_for_exam/', examinationViews.register_for_exam, name="register_for_exam"),


    #COMMUNICATION MANAGEMENT
    path('academics_comm_save/', academicsViews.academics_comm_save, name="academics_comm_save"),
    

    # UTILITY URLS
    path('check_class_exist/', classView.check_class_exist, name="check_class_exist"),
    path('check_cluster_class_exist/', classView.check_cluster_class_exist, name="check_cluster_class_exist")

]

core/urls.py
from django.urls import path, include

from academics.subviews import classView, studentView
from iSOFTLIMS import utils
from . import views
from core.subviews import AdminViews, StudentViews, StudentAdminAffairs, ApplicantViews, UserViews
from django.contrib.auth import views as auth_views

urlpatterns = [
    # HOMEPAGE URL
    path("", views.loginPage, name="login"),
    path("login", views.loginPage, name="login"),
    path("register/", views.applicantloginPage, name="register"),
    path("doSignUp/", ApplicantViews.applicantsignup, name="doSignUp"),  # type: ignore
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("applicant_home/", ApplicantViews.applicant_home, name="applicant_home"),  # type: ignore
    path("user_home/", UserViews.user_home, name="user_home"),

    # USER CRUD URLS
    path("doLogin/", views.doLogin, name="doLogin"),
    path("get_user_details/", views.get_user_details, name="get_user_details"),
    path("logout_user/", views.logout_user, name="logout_user"),
    path("activate_account", views.activate_account, name="activate_account"),
    path("activate_user/<user_id>", AdminViews.activate_user, name="activate_user"),
    path(
        "deactivate_user/<user_id>", AdminViews.deactivate_user, name="deactivate_user"
    ),

    # ADMIN URLS
    path("admin_home/", AdminViews.admin_home, name="admin_home"),
    path("manage_users/", AdminViews.manage_users, name="manage_users"),

    # SCHOOL PROFILE URLS
    path("admin_profile/", AdminViews.admin_profile, name="admin_profile"),
    path("admin_profile_update/", AdminViews.admin_profile_update, name="admin_profile_update"),
    path("school_profile/", AdminViews.school_profile, name="school_profile"),
    path("admin_school_update/", AdminViews.admin_school_update, name="admin_school_update"),

    # ADMINISTRATION URLS:
    path("administration/", AdminViews.administration, name="administration"),
    path("add_campus/", AdminViews.add_campus, name="add_campus"),
    path("edit_campus/<campus_id>", AdminViews.edit_campus, name="edit_campus"),
    path("delete_campus/<campus_id>", AdminViews.delete_campus, name="delete_campus"),
    path("schools/", AdminViews.school, name="schools"),
    path("add_school/", AdminViews.add_school, name="add_school"),
    path("edit_school/<school_id>", AdminViews.edit_school, name="edit_school"),
    path("delete_school/<school_id>", AdminViews.delete_school, name="delete_school"),

    # ADMISSIONS
    path("admissions/", AdminViews.admissions, name="admissions"),
    path("admissions_approve/", AdminViews.admissions_approve, name="admissions_approve"),
    path("dvc_approve/", AdminViews.dvc_approve, name="dvc_approve"),

    # DEPARTMENT MANAGEMENT URLS
    path("manage_department/", AdminViews.manage_departments, name="manage_departments"),
    path("add_department/", AdminViews.add_department, name="add_department"),
    path("add_department_save/", AdminViews.add_department_save, name="add_department_save"),
    path("edit_department/<department_id>/", AdminViews.edit_department, name="edit_department"),
    path("edit_department_save/", AdminViews.edit_department_save, name="edit_department_save"),
    path("delete_department/<department_id>/", AdminViews.delete_department, name="delete_department"),
    path("manage_staff_type/", AdminViews.manage_staff_type, name="manage_staff_type"),
    path("create_staff_type/", AdminViews.create_staff_type, name="create_staff_type"),

    # HOD URLS
    path("manage_hod/", AdminViews.manage_hods, name="manage_hod"),
    path("add_hod/", AdminViews.add_hod, name="add_hod"),
    path("add_hod_save/", AdminViews.add_hod_save, name="add_hod_save"),
    path("edit_hod/<hod_id>/", AdminViews.edit_hod, name="edit_hod"),
    path("edit_hod_save/", AdminViews.edit_hod_save, name="edit_hod_save"),
    path("delete_hod/<hod_id>/", AdminViews.delete_hod, name="delete_hod"),

    # MANAGE COURSE
    path("manage_courses/", AdminViews.manage_courses, name="manage_courses"),
    path("add_course/", AdminViews.add_course, name="add_course"),
    path("add_course_save/", AdminViews.add_course_save, name="add_course_save"),
    path("check_if_course_exists/", AdminViews.check_if_course_exists, name="check_if_course_exists"),
    path("edit_course/<course_id>", AdminViews.edit_course, name="edit_course"),
    path("delete_course/<course_id>", AdminViews.delete_course, name="delete_course"),

    # STAFF URLS
    path("add_staff/", AdminViews.add_staff, name="add_staff"),
    path("add_staff_save/", AdminViews.add_staff_save, name="add_staff_save"),
    path("manage_staff/", AdminViews.manage_staff, name="manage_staff"),
    path("edit_staff/<staff_id>/", AdminViews.edit_staff, name="edit_staff"),
    path("edit_teacher/<teacher_id>/", AdminViews.edit_teacher, name="edit_teacher"),
    path("edit_staff_save/", AdminViews.edit_staff_save, name="edit_staff_save"),
    path("edit_teacher_save/", AdminViews.edit_teacher_save, name="edit_teacher_save"),
    path("delete_staff/<staff_id>/", AdminViews.delete_staff, name="delete_staff"),
    path("delete_teacher/<teacher_id>/", AdminViews.delete_teacher, name="delete_teacher"),

    # STUDENT URLS
    path("student_home", StudentViews.student_home, name="student_home"),
    path("student_profile/", StudentViews.student_profile, name="student_profile"),
    path("student_sessions/", StudentViews.enroll_session, name="enroll_session"),
    path("enroll_session_save/<enrollment_id>", StudentViews.enroll_session_save, name="enroll_session_save"),
    path("student_classes/", StudentViews.enroll_classes, name="enroll_classes"),
    path("enroll_class_save/", StudentViews.enroll_class_save, name="enroll_class_save"),
    path("student_apply_leave/", StudentViews.student_apply_leave, name="student_apply_leave"),
    path("student_apply_leave_save/", StudentViews.student_apply_leave_save, name="student_apply_leave_save"),
    path("student_feedback/", StudentViews.student_feedback, name="student_feedback"),
    path("student_feedback_save/", StudentViews.student_feedback_save, name="student_feedback_save"),
    path("student_profile/", StudentViews.student_profile, name="student_profile"),
    path("student_profile_update/", StudentViews.student_profile_update, name="student_profile_update"),
    path("student_view_result/", StudentViews.student_view_result, name="student_view_result"),

    path("student_housing/", StudentViews.student_housing, name="student_housing"),
    path("book_housing/<house_id>", StudentViews.book_housing, name="book_housing"),
    



    path("add_student/", AdminViews.add_student, name="add_student"),
    path("add_student_save/", AdminViews.add_student_save, name="add_student_save"),
    path("edit_student/<student_id>", AdminViews.edit_student, name="edit_student"),
    path("edit_student_save/", AdminViews.edit_student_save, name="edit_student_save"),
    path("manage_students/", AdminViews.manage_students, name="manage_students"),
    path("delete_student/<student_id>/", AdminViews.delete_student, name="delete_student"),
    path("student_session_management/", StudentViews.students_sessions_management, name="students_sessions_management"),
    path("defer_student/", StudentViews.defer_student, name="defer_student"),
    path("withdraw_student/", StudentViews.withdraw_student, name="withdraw_student"),
    path("student_affairs/", StudentAdminAffairs.student_affairs_home, name="student_affairs"),
    path("manage_student_approvals/", StudentAdminAffairs.manage_student_approvals, name="manage_student_approvals"),
    path("confirm_defer_student/", StudentAdminAffairs.confirm_defer_student, name="confirm_defer_student"),
    path("deny_defer_student/", StudentAdminAffairs.deny_defer_student, name="deny_defer_student"),
    path("manage_temporary_approvals/", StudentAdminAffairs.manage_temporary_approvals, name="manage_temporary_approvals"),
    path("confirm_temporary_defer/", StudentAdminAffairs.confirm_temporary_defer, name="confirm_temporary_defer"),
    path("deny_temporary_defer/", StudentAdminAffairs.deny_temporary_defer, name="deny_temporary_defer"),
    path("manage_interfaculty_transfer/", StudentAdminAffairs.manage_interfaculty_transfer, name="manage_interfaculty_transfer"),
    path("confirm_interfaculty_transfer/", StudentAdminAffairs.confirm_interfaculty_transfer, name="confirm_interfaculty_transfer"),
    path("deny_interfaculty_transfer/", StudentAdminAffairs.deny_interfaculty_transfer, name="deny_interfaculty_transfer"),
    path("manage_guardians/", AdminViews.manage_guardians, name="manage_guardians"),
    path("add_guardians/", AdminViews.add_guardian, name="add_guardian"),
    path("add_guardian_save/", AdminViews.add_guardian_save, name="add_guardian_save"),
    path("edit_guardian/<guardian_id>/", AdminViews.edit_guardian, name="edit_guardian"),
    path("edit_guardian_save/", AdminViews.edit_guardian_save, name="edit_guardian_save"),
    path("delete_guardian/<guardian_id>/", AdminViews.delete_student, name="delete_guardian"),

    path("apply_interschool_transfer/", StudentAdminAffairs.apply_interschool_transfer, name="apply_interschool_transfer"),

iSOFTLIMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.defaults import page_not_found
from django.contrib import admin


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("academics/", include("academics.urls")),
    path("finance/", include("finance.urls")),
    # zesting the inbuilt forms to add custom autocomplete
    path("select2/", include("django_select2.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, )+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'iSOFTLIMS.views.handler404'
handler500 = 'iSOFTLIMS.views.handler500'

admin.site.site_header = 'iSoft ADMINISTRATION'
admin.site.site_title = 'iSOFT'

academics/forms/clusterforms.py
from django import forms
from academics.models import Class, ClusterClass

class ClusterClassForm(forms.ModelForm):
    classes = forms.ModelMultipleChoiceField(queryset=Class.objects.all(), required=False, widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = ClusterClass
        fields = ['cluster_class_name', 'classes']

    # def save(self, commit=True, force_insert=False):
    #     instance = super().save(commit=False)
    #     if commit:
    #         instance. super().save()
    #         self.save_m2m()
    #     return instance

academics/forms/communicationForms.py
from django import forms
from academics.models import AcademicCommunications


class AcademicCommunicationForm(forms.ModelForm):
    class Meta:
        model = AcademicCommunications
        fields = '__all__'

academics/forms/sessionforms.py
from django import forms
from academics.models import Enrollment, Session

class EnrollmentCreateForm(forms.ModelForm):
    class Meta: 
        model = Enrollment
        fields = '__all__'



class SessionEditForm(forms.ModelForm):

    session_start_date = forms.DateField(
        widget=forms.TextInput(attrs={'type': 'date'})
    )
    session_end_date = forms.DateField(
        widget=forms.TextInput(attrs={'type': 'date'})
    )
    class Meta:
        model = Session
        fields = ('session_start_date', 'session_end_date', 'is_current')

academics/views.py
from django.shortcuts import render

# Create your views here.

academics/templates/session_templates/add_session_template.html
{% extends 'base_template.html' %}

{% block page_title %}
    Add Session Year
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Add Session Period</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form role="form" method="POST" action="{% url 'academics:add_session_save' %}">
                        {% csrf_token %}

                        
                                {% comment %} Display Messages {% endcomment %}
                                {% if messages %}
                                <div class="form-group">
                                <div class="col-12">
                                    {% for message in messages %}
                                    {% if message.tags == "error" %}
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% elif message.tags == "success" %}
                                        <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                        {{ message }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        </div>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                                </div>
                                {% endif %}
                            

                        <div class="card-body">
                            <div class="form-group">
                                <label>Session Start Period:</label>
                                <input type="date" class="form-control" name="session_start_date">
                            </div>

                            <div class="form-group">
                                <label>Session End Period:</label>
                                <input type="date" class="form-control" name="session_end_date">
                            </div>

                            <div class="form-group">
                                <label for="is_current">Is Current:</label>
                                <div class="form-check">
                                  <input type="checkbox" class="form-check-input" id="is_current" name="is_current">
                                  <label class="form-check-label" for="is_current">Yes</label>
                                </div>
                              </div>
                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Add Session</button>
                        </div>
                    </form>
                    </div>
                    <!-- /.card -->

                </div>
            </div>

        </div><!-- /.container-fluid -->
      </section>

  {% endblock main_content %}

academics/templates/session_templates/manage_session_registration_template.html
{% extends 'base_template.html' %}

{% block page_title %}
Manage Enrolled Students
{% endblock page_title %}

{% block main_content %}

{% load static %}

<section class="content">
    <div class="container-fluid">

        <a class="btn btn-primary" href="{% url 'academics:enroll_student' %}" role="button">Enroll a student</a> <br />&nbsp;

        {% if messages %}
        <div class="form-group">
            <div class="col-12">
                {% for message in messages %}
                {% if message.tags == "error" %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% elif message.tags == "success" %}
                <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% elif message.tags == "warning" %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endif %}

        <div class="row">

            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Current Session Registrants</h3>

                        <div class="card-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control float-right"
                                    placeholder="Search">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                        <div class="row justify-content-between mx-2 my-2">
                            <div> 
                                <button id="select-all-btn" class="btn btn-primary">Select All</button>
                            </div>
                            <div>
                                <button id="mass-edit-btn" class="btn btn-primary mx-2 my-2">Enroll Selected Students</button>
                            </div>
                        </div>
                        <table class="table table-hover text-nowrap">
                            
                            <thead>
                                <tr>
                                    <th>Session</th>
                                    <th>Student</th>
                                    <th>Enrollment Date</th>
                                    <th>Select to Enroll</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% csrf_token %}
                                {% for enrolled in currently_enrolled %}
                                <tr>
                                    <td>{{ enrolled.session}}</td>
                                    <td>{{ enrolled.student.name}}</td>
                                    <td>{{ enrolled.enrollment_date }}</td>
                                    <td>
                                        {% if not enrolled.is_active %}
                                        <input type="checkbox" name="enrolled_ids[]" value="{{ enrolled.id }}">
                                        {% endif %}
                                        {% if enrolled.is_active %}
                                        <button disabled href="{% url 'academics:confirm_enrollment' enrolled.id %}"
                                            class="btn btn-success">Student Enrolled</button>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if not enrolled.is_active %}
                                        <a href="{% url 'academics:revoke_enrollment' enrolled.id %}"
                                            class="btn btn-danger disabled">Revoke Enrollment</a>
                                        {% else %}
                                        <a href="{% url 'academics:revoke_enrollment' enrolled.id %}"
                                            class="btn btn-danger">Revoke Enrollment</a>
                                        {% endif %}

                                    </td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </div>
        </div>

    </div><!-- /.container-fluid -->
</section>

{% endblock main_content %}

{% block custom_js %}

{% comment %}
With these changes, the "Select All" button will check all checkboxes in the table, and only unchecked checkboxes will be included in the mass edit action.
{% endcomment %}

<script>
    const csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;

    const massEditBtn = document.querySelector('#mass-edit-btn');
    const selectAllBtn = document.querySelector('#select-all-btn');
    const enrolledIdsCheckboxes = document.querySelectorAll('input[name="enrolled_ids[]"]');

    const enrolledIds = [];

    enrolledIdsCheckboxes.forEach((checkbox) => {
        if (checkbox.checked) {
            enrolledIds.push(checkbox.value);
        }
    });

    selectAllBtn.addEventListener('click', () => {
        Array.from(enrolledIdsCheckboxes).forEach((checkbox) => {
            checkbox.checked = true;
        });
    });

    massEditBtn.addEventListener('click', (e) => {
        e.preventDefault();
        const enrolledIds = Array.from(enrolledIdsCheckboxes)
            .filter((checkbox) => checkbox.checked)
            .map((checkbox) => checkbox.value);

        console.log('enrolled ids is ' + enrolledIds)

        if (enrolledIds.length > 0) {
            //const formData = new FormData();
            //formData.append('enrolled_ids', enrolledIds.join(','));
            //formData.append('is_active', 'true');

            const formData = new FormData();
            enrolledIds.forEach((id) => {
                formData.append('enrolled_ids[]', id);
            });

            console.log(formData)

            fetch('{% url 'academics:mass_edit_enrolled' %}', {
                method: 'POST',
                body: formData,
                headers: {
                    'X-CSRFToken': csrfToken
                }
            }).then((response) => {
                if (response.ok) {
                    location.reload();
                }
            });
        }
    });
</script>

{% endblock custom_js %}