core/urls.py
from django.urls import path, include

from academics.subviews import classView, studentView
from iSOFTLIMS import utils
from . import views
from core.subviews import AdminViews, StudentViews, StudentAdminAffairs, ApplicantViews, UserViews
from django.contrib.auth import views as auth_views

urlpatterns = [
    # HOMEPAGE URL
    path("", views.loginPage, name="login"),
    path("login", views.loginPage, name="login"),
    path("register/", views.applicantloginPage, name="register"),
    path("doSignUp/", ApplicantViews.applicantsignup, name="doSignUp"),  # type: ignore
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("applicant_home/", ApplicantViews.applicant_home, name="applicant_home"),  # type: ignore
    path("user_home/", UserViews.user_home, name="user_home"),

    # USER CRUD URLS
    path("doLogin/", views.doLogin, name="doLogin"),
    path("get_user_details/", views.get_user_details, name="get_user_details"),
    path("logout_user/", views.logout_user, name="logout_user"),
    path("activate_account", views.activate_account, name="activate_account"),
    path("activate_user/<user_id>", AdminViews.activate_user, name="activate_user"),
    path(
        "deactivate_user/<user_id>", AdminViews.deactivate_user, name="deactivate_user"
    ),

    # ADMIN URLS
    path("admin_home/", AdminViews.admin_home, name="admin_home"),
    path("manage_users/", AdminViews.manage_users, name="manage_users"),

    # SCHOOL PROFILE URLS
    path("admin_profile/", AdminViews.admin_profile, name="admin_profile"),
    path("admin_profile_update/", AdminViews.admin_profile_update, name="admin_profile_update"),
    path("school_profile/", AdminViews.school_profile, name="school_profile"),
    path("admin_school_update/", AdminViews.admin_school_update, name="admin_school_update"),

    # ADMINISTRATION URLS:
    path("administration/", AdminViews.administration, name="administration"),
    path("add_campus/", AdminViews.add_campus, name="add_campus"),
    path("edit_campus/<campus_id>", AdminViews.edit_campus, name="edit_campus"),
    path("delete_campus/<campus_id>", AdminViews.delete_campus, name="delete_campus"),
    path("schools/", AdminViews.school, name="schools"),
    path("add_school/", AdminViews.add_school, name="add_school"),
    path("edit_school/<school_id>", AdminViews.edit_school, name="edit_school"),
    path("delete_school/<school_id>", AdminViews.delete_school, name="delete_school"),

    # ADMISSIONS
    path("admissions/", AdminViews.admissions, name="admissions"),
    path("admissions_approve/", AdminViews.admissions_approve, name="admissions_approve"),
    path("dvc_approve/", AdminViews.dvc_approve, name="dvc_approve"),

    # DEPARTMENT MANAGEMENT URLS
    path("manage_department/", AdminViews.manage_departments, name="manage_departments"),
    path("add_department/", AdminViews.add_department, name="add_department"),
    path("add_department_save/", AdminViews.add_department_save, name="add_department_save"),
    path("edit_department/<department_id>/", AdminViews.edit_department, name="edit_department"),
    path("edit_department_save/", AdminViews.edit_department_save, name="edit_department_save"),
    path("delete_department/<department_id>/", AdminViews.delete_department, name="delete_department"),
    path("manage_staff_type/", AdminViews.manage_staff_type, name="manage_staff_type"),
    path("create_staff_type/", AdminViews.create_staff_type, name="create_staff_type"),

    # HOD URLS
    path("manage_hod/", AdminViews.manage_hods, name="manage_hod"),
    path("add_hod/", AdminViews.add_hod, name="add_hod"),
    path("add_hod_save/", AdminViews.add_hod_save, name="add_hod_save"),
    path("edit_hod/<hod_id>/", AdminViews.edit_hod, name="edit_hod"),
    path("edit_hod_save/", AdminViews.edit_hod_save, name="edit_hod_save"),
    path("delete_hod/<hod_id>/", AdminViews.delete_hod, name="delete_hod"),

    # MANAGE COURSE
    path("manage_courses/", AdminViews.manage_courses, name="manage_courses"),
    path("add_course/", AdminViews.add_course, name="add_course"),
    path("add_course_save/", AdminViews.add_course_save, name="add_course_save"),
    path("check_if_course_exists/", AdminViews.check_if_course_exists, name="check_if_course_exists"),
    path("edit_course/<course_id>", AdminViews.edit_course, name="edit_course"),
    path("delete_course/<course_id>", AdminViews.delete_course, name="delete_course"),

    # STAFF URLS
    path("add_staff/", AdminViews.add_staff, name="add_staff"),
    path("add_staff_save/", AdminViews.add_staff_save, name="add_staff_save"),
    path("manage_staff/", AdminViews.manage_staff, name="manage_staff"),
    path("edit_staff/<staff_id>/", AdminViews.edit_staff, name="edit_staff"),
    path("edit_teacher/<teacher_id>/", AdminViews.edit_teacher, name="edit_teacher"),
    path("edit_staff_save/", AdminViews.edit_staff_save, name="edit_staff_save"),
    path("edit_teacher_save/", AdminViews.edit_teacher_save, name="edit_teacher_save"),
    path("delete_staff/<staff_id>/", AdminViews.delete_staff, name="delete_staff"),
    path("delete_teacher/<teacher_id>/", AdminViews.delete_teacher, name="delete_teacher"),

    # STUDENT URLS
    path("student_home", StudentViews.student_home, name="student_home"),
    path("student_profile/", StudentViews.student_profile, name="student_profile"),
    path("student_sessions/", StudentViews.enroll_session, name="enroll_session"),
    path("enroll_session_save/<enrollment_id>", StudentViews.enroll_session_save, name="enroll_session_save"),
    path("student_classes/", StudentViews.enroll_classes, name="enroll_classes"),
    path("enroll_class_save/", StudentViews.enroll_class_save, name="enroll_class_save"),
    path("student_apply_leave/", StudentViews.student_apply_leave, name="student_apply_leave"),
    path("student_apply_leave_save/", StudentViews.student_apply_leave_save, name="student_apply_leave_save"),
    path("student_feedback/", StudentViews.student_feedback, name="student_feedback"),
    path("student_feedback_save/", StudentViews.student_feedback_save, name="student_feedback_save"),
    path("student_profile/", StudentViews.student_profile, name="student_profile"),
    path("student_profile_update/", StudentViews.student_profile_update, name="student_profile_update"),
    path("student_view_result/", StudentViews.student_view_result, name="student_view_result"),

    path("student_housing/", StudentViews.student_housing, name="student_housing"),
    path("book_housing/<house_id>", StudentViews.book_housing, name="book_housing"),
    



    path("add_student/", AdminViews.add_student, name="add_student"),
    path("add_student_save/", AdminViews.add_student_save, name="add_student_save"),
    path("edit_student/<student_id>", AdminViews.edit_student, name="edit_student"),
    path("edit_student_save/", AdminViews.edit_student_save, name="edit_student_save"),
    path("manage_students/", AdminViews.manage_students, name="manage_students"),
    path("delete_student/<student_id>/", AdminViews.delete_student, name="delete_student"),
    path("student_session_management/", StudentViews.students_sessions_management, name="students_sessions_management"),
    path("defer_student/", StudentViews.defer_student, name="defer_student"),
    path("withdraw_student/", StudentViews.withdraw_student, name="withdraw_student"),
    path("student_affairs/", StudentAdminAffairs.student_affairs_home, name="student_affairs"),
    path("manage_student_approvals/", StudentAdminAffairs.manage_student_approvals, name="manage_student_approvals"),
    path("confirm_defer_student/", StudentAdminAffairs.confirm_defer_student, name="confirm_defer_student"),
    path("deny_defer_student/", StudentAdminAffairs.deny_defer_student, name="deny_defer_student"),
    path("manage_temporary_approvals/", StudentAdminAffairs.manage_temporary_approvals, name="manage_temporary_approvals"),
    path("confirm_temporary_defer/", StudentAdminAffairs.confirm_temporary_defer, name="confirm_temporary_defer"),
    path("deny_temporary_defer/", StudentAdminAffairs.deny_temporary_defer, name="deny_temporary_defer"),
    path("manage_interfaculty_transfer/", StudentAdminAffairs.manage_interfaculty_transfer, name="manage_interfaculty_transfer"),
    path("confirm_interfaculty_transfer/", StudentAdminAffairs.confirm_interfaculty_transfer, name="confirm_interfaculty_transfer"),
    path("deny_interfaculty_transfer/", StudentAdminAffairs.deny_interfaculty_transfer, name="deny_interfaculty_transfer"),
    path("manage_guardians/", AdminViews.manage_guardians, name="manage_guardians"),
    path("add_guardians/", AdminViews.add_guardian, name="add_guardian"),
    path("add_guardian_save/", AdminViews.add_guardian_save, name="add_guardian_save"),
    path("edit_guardian/<guardian_id>/", AdminViews.edit_guardian, name="edit_guardian"),
    path("edit_guardian_save/", AdminViews.edit_guardian_save, name="edit_guardian_save"),
    path("delete_guardian/<guardian_id>/", AdminViews.delete_student, name="delete_guardian"),

    path("apply_interschool_transfer/", StudentAdminAffairs.apply_interschool_transfer, name="apply_interschool_transfer"),

finance/urls.py
from django.urls import path, include
from . import views
from finance import views
from .subviews import MainViews

app_name = "finance"


urlpatterns = [
    # path("finance", views.finance_home, name="finance_home"),
    path("", views.finance_home, name="finance_home"),
    path("add_transaction", views.add_transaction, name="add_transaction"),
    path("transaction_create", views.transaction_create, name='transaction_create'),
    path('approve_applications/', views.approve_applications, name="approve_applications"),
    path('approve/', views.approve, name="approve"),
    path('check_student_exist/', views.check_student_exist, name="check_student_exist"),

    # PAYMENT METHODS
    path("manage_payment_methods", MainViews.manage_payment_methods, name="manage_payment_methods"),
    path("add_payment_method", MainViews.add_payment_method, name="add_payment_method"),
    path("add_payment_method_save", MainViews.add_payment_method_save, name="add_payment_method_save"),
    path("edit_payment_method/<payment_method_id>", MainViews.edit_payment_method, name="edit_payment_method"),
    path("delete_payment_method/<payment_method_id>", MainViews.delete_payment_method, name="delete_payment_method"),
    # banks
    path("manage_banks", MainViews.manage_banks, name="manage_banks"),
    path("add_bank", MainViews.add_bank, name="add_bank"),
    path("add_bank_save", MainViews.add_bank_save, name="add_bank_save"),
    path("edit_bank/<bank_id>", MainViews.edit_bank, name="edit_bank"),
    path("delete_bank/<bank_id>", MainViews.delete_bank, name="delete_bank"),

    # billing ITEMS
    path("manage billing", MainViews.manage_billing_items, name="manage_billing_items"),
    path("add_billing_item", MainViews.add_billing_item, name="add_billing_item"),
    path("add_billing_item_save", MainViews.add_billing_item_save, name="add_billing_item_save"),
    path("edit_billing_item/<billing_item_id>", MainViews.edit_billing_item, name="edit_billing_item"),
    path("delete_billing_item/<billing_item_id>", MainViews.delete_billing_item, name="delete_billing_item"),

    # BILLING TEMPLATES
    path("manage_billing_templates", MainViews.manage_billing_templates, name="manage_billing_templates"),
    path("add_billing_template", MainViews.add_billing_template, name="add_billing_template"),
    path("add_billing_template_save", MainViews.add_billing_template_save, name="add_billing_template_save"),
    path("edit_billing_template/<billing_template_id>", MainViews.edit_billing_template, name="edit_billing_template"),
    path("delete_billing_template/<billing_template_id>", MainViews.delete_billing_template, name="delete_billing_template"),

    # STUDENT VIEWS
    # path("manage_billings/", MainViews.manage_billings, name="manage_billings"),
]

iSOFTLIMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.defaults import page_not_found
from django.contrib import admin


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("academics/", include("academics.urls")),
    path("finance/", include("finance.urls")),
    # zesting the inbuilt forms to add custom autocomplete
    path("select2/", include("django_select2.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, )+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'iSOFTLIMS.views.handler404'
handler500 = 'iSOFTLIMS.views.handler500'

admin.site.site_header = 'iSoft ADMINISTRATION'
admin.site.site_title = 'iSOFT'

finance/forms/billingtemplatesforms.py
from django import forms
from academics.models import Course
from finance.models import BillingTemplate, CurriculumSystem, BillingItem, Program, School

class BillingTemplateForm(forms.ModelForm): 
    code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    faculty_or_school = forms.ModelChoiceField(label="Faculty or School", queryset=School.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), required=False)
    program = forms.ModelChoiceField(label="Program", queryset=Program.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), required=False)
    system = forms.ModelChoiceField(label="System", queryset=CurriculumSystem.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), required=False)
    course = forms.ModelChoiceField(label="Course", queryset=Course.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), required=False)
    class_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    sponsorship_type = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    year_of_study = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    # billing_item = forms.ModelChoiceField(label="Billing Item", queryset=BillingItem.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), required=False)

    # fee_item_amount = forms.IntegerField(label="Fee Item Ammount", widget=forms.TextInput(attrs={"class": "form-control"}), required=False)

    gl_statement_prefix = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    notes = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = BillingTemplate
        fields = '__all__'


class EditBillingTemplateForm(forms.ModelForm):
    code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    faculty_or_school = forms.ModelChoiceField(label="Faculty or School", queryset=School.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), required=False)
    program = forms.ModelChoiceField(label="Program", queryset=Program.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), required=False)
    system = forms.ModelChoiceField(label="System", queryset=CurriculumSystem.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), required=False)
    course = forms.ModelChoiceField(label="Course", queryset=Course.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), required=False)
    class_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    sponsorship_type = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    year_of_study = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    fee_item = forms.ModelChoiceField(label="Fee Item", queryset=BillingItem.objects.all(), widget=forms.Select(attrs={"class": "form-control"}), required=False)

    fee_item_amount = forms.IntegerField(label="Fee Item Ammount", widget=forms.TextInput(attrs={"class": "form-control"}), required=False)

    gl_statement_prefix = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    notes = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = BillingTemplate
        fields = '__all__'

finance/forms/transactionForms.py
from django import forms
from finance.models import Transaction

class CreateTransactionForm(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = '__all__'

finance/templates/finance/add_transaction.html
{% extends 'finance/base_template.html' %}

{% block page_title %}
Add Transaction
{% endblock page_title %}

{% block main_content %}


{% load static %}

<div class="container-fluid">

    <div class="row">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Add Transactions</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                {% url 'finance:transaction_create' as action_path %}
                {% include 'finance/form_template.html' with messages=messages form=form action_path=action_path button_text="Add Transaction" %}

            </div>
            <!-- /.card -->

        </div>
    </div>

</div>

{% endblock main_content %}

finance/templates/finance/form_template.html
<form role="form" method="POST" action="{{ action_path }}" enctype="multipart/form-data">
    {% csrf_token %}


    {% comment %} Display Messages {% endcomment %}
    {% if messages %}
    <div class="form-group">
        <div class="col-12">
            {% for message in messages %}
            {% if message.tags == "error" %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% elif message.tags == "success" %}
            <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endif %}

    <div class="card-body">

        {% comment %} Adding Form with All inputs Here {% endcomment %}

        {% for field in form %}
        <div class="form-group">

            <div class="form-group">
                {{ field.errors }}
                <label class="control-label col-sm-3">{{ field.label_tag }}</label>
                <div class="col-sm-9">
                    {{ field }}
                </div>
            </div>

        </div>
        {% endfor %%}




    </div>
    <!-- /.card-body -->

    <div class="card-footer">
        <button type="submit" class="btn btn-primary">{{ button_text }}</button>
    </div>
</form>

finance/templates/finance/manage_payment_methods_template.html
{% extends 'admin_template/base_template.html' %} 
{% block page_title %} 
<b>Manage Manage Payments</b> 
{% endblock page_title %} 
{% block main_content %}
{% load static %}

<section class="content">
    <div class="container-fluid">
        
        <div class="mx-auto row">

            {% include 'core_navigation_navbar.html' %}

        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="mx-auto row ">
                    <div class="mr-1">
                        <a class="btn btn-primary" href="{% url 'finance:add_payment_method' %}" role="button"> Create Payment</a><br/>&nbsp;
                    </div>
                    <div class="mr-3">
                        <a class="btn btn-primary" href="{% url 'finance:manage_banks' %}" role="button"> Manage Banks</a><br/>&nbsp;
                    </div>
                </div> 
                <!-- general form elements -->
                <div class="card card-primary">

                    <div class="card-body">

                        {% if messages %}
                        <div class="form-group">
                            <div class="col-12">
                                {% for message in messages %}
                                {% if message.tags == "error" %}
                                <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% elif message.tags == "success" %}
                                <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% elif message.tags == "warning" %}
                                <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                        {% endif %}

                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Manage Payments</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <div class="card-body">
                                <table class="table table-hover text-wrap">
                                    <thead>
                                        <tr>
                                            <th>Code</th>
                                            <th>Name</th>
                                            <th>Description</th>
                                            <th>Default Bank Account</th>
                                            <th>Actions</th>
                                            
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for payment_method in payment_methods %}
                                        <tr>
                                            <td>{{ payment_method.code }}</td>
                                            <td>{{ payment_method.name }}</td>
                                            <td>{{ payment_method.description }}</td>
                                            <td>{{ payment_method.default_bank_account }}</td>
                                            

                                            <td>
                                                <button class="btn btn-primary" data-toggle="collapse"
                                                    data-target="#form{{ payment_method.id }}">Details</button>
                                            </td>
                                        </tr>
    
                                        <tr>
                                            <td colspan="8">
                                                <div id="form{{ payment_method.id }}" class="form-row collapse">
                                                    <div>
                                                    </div>
                                                    <div class="card col-md-6 my-3">
                                                        <div class="container my-3">
                                                            <h3 class="text-bold">Payment Methods:</h3>
                                                            <hr>
                                                            <div class="">
                                                                <div class="">
                                                                    <div>
                                                                        <h5><strong>Transactions:</strong></h5>
                                                                        <hr>
                                                                        {{ payment_method.transaction_reference_required }}
                                                                    </div>
                                                                    <br>

                                                                    <div>
                                                                        <h5><strong>GL Account:</strong></h5>
                                                                        <hr>
                                                                        {{ payment_method.unit_of_measure_required }}
                                                                    </div>

                                                                    <br>

                                                                    <div>
                                                                        <h5><strong>On hold:</strong></h5>
                                                                        <hr>
                                                                        {{ payment_method.on_hold_disable_posting_on_item }}
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
    
                                                    <div class="col-md-6 my-3">
                                                        <div class="card rowss">
                                                            <h3 class="mx-3 my-3 text-bold">Other Details:
                                                            </h3>
                                                            <hr>
                                                            <div class="mx-3">
                                                                <div class="">
                                                                    <div>
                                                                        <h5><strong>GL Account:</strong></h5>
                                                                        <hr>
                                                                        {{ payment_method.gl_account }}
                                                                    </div>
                                                                    <div>
                                                                        <h5><strong>Notes</strong></h5>
                                                                        <hr>
                                                                        {{ payment_method.notes }}
                                                                    </div>
                                                                    <br>
                                                                    
                                                                    <div class="mb-2">
                                                                        <a class="btn btn-success" href="{% url 'finance:edit_payment_method' payment_method.id %}" role="button">
                                                                            Edit Transaction</a>
                                                                    </div>
                                                                    <div class="mb-1">
                                                                        <a class="btn btn-danger" href="{% url 'finance:delete_payment_method' payment_method.id %}" role="button">
                                                                            Delete</a>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                        </tr>
                                        {% empty %}
                                        <tr>
                                            <td colspan="10">No payment methods available.</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</section>

{% endblock main_content %}